files:
  - source: /translations/**/en/*.pot
    translation: /translations/**/%two_letters_code%/%two_letters_code%_%file_name%.po
  - source: /translations/**/en/*.docx
    translation: /translations/**/%two_letters_code%/%two_letters_code%_%file_name%.docx
  - source: /translations/**/en/*.csv
    translation: /translations/**/%two_letters_code%/%two_letters_code%_%file_name%.csv
  - source: /translations/**/en/*.pptx
    translation: /translations/**/%two_letters_code%/%two_letters_code%_%file_name%.pptx
